domain: {{appName}}__STAGE__.meh.greenhousegroup.com
email: meh@greenhousegroup.com
version: __VERSION__
dockerImage: registry.gitlab.com/{{gitlabNamespace}}/{{appName}}:__VERSION__
webReplicas: __REPLICAS__
ingress:
  createIngress: true
  pingdom: {{pingdom}}
  tls: true
  annotations:
    certmanager.k8s.io/cluster-issuer: letsencrypt-prod
containerResources:
  limits:
    memory: '256M'
    cpu: 100m
envSecretName: {{appName}}__STAGE__-secret-env
